
[[constraint]]
  branch = "master"
  name = "github.com/xwb1989/sqlparser"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.4.2"
